name: seqsender
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - blas=2.3=openblas
  - certifi=2016.9.26=py36_0
  - libblas=3.9.0=3_openblas
  - libcblas=3.9.0=3_openblas
  - liblapack=3.9.0=3_openblas
  - liblapacke=3.9.0=3_openblas
  - pip=21.2.4=pyhd8ed1ab_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.6=2_cp36m
  - pytz=2022.1=pyhd8ed1ab_0
  - requests=2.12.5=py36_0
  - six=1.16.0=pyh6c4a22f_0
  - wheel=0.37.1=pyhd8ed1ab_0
  
  - pip:
    - biopython==1.79
    - Bio
    - pandas
    - yaml
 
    
 


